#!/usr/bin/env python3

import os
import subprocess
import sys
from types import SimpleNamespace

all_checks = [
    SimpleNamespace(flag="-print-ast", extension=".ast", is_default=False),
    SimpleNamespace(flag="-print-ir", extension=".ir", is_default=True),
    SimpleNamespace(flag="-print-llvm", extension=".ll", is_default=True),
]

cx, test_file, *cx_flags = sys.argv[1:]

checks_to_run = ([c for c in all_checks if c.flag in cx_flags]
                 or [c for c in all_checks if c.is_default])

for check in checks_to_run:
    snapshot_path = test_file + check.extension

    try:
        output = subprocess.check_output(sys.argv[1:] + [check.flag], text=True)
    except subprocess.CalledProcessError as error:
        print(error.output)
        sys.exit(error.returncode)

    if "UPDATE_SNAPSHOTS" in os.environ:
        with open(snapshot_path, "w") as snapshot_file:
            snapshot_file.write(output)
        continue

    try:
        with open(snapshot_path, "r") as snapshot_file:
            snapshot = snapshot_file.read().replace("\r\n", "\n")
    except IOError:
        print("FAIL: snapshot file not found\n")
        print("Output:")
        print(output)
        sys.exit(1)

    if output != snapshot:
        print("FAIL: output doesn't match snapshot\n")
        print("- Snapshot")
        print("+ Received\n")

        import difflib

        diff = difflib.unified_diff(snapshot.splitlines(1), output.splitlines(1))
        print("".join(diff))

        sys.exit(1)
