#!/usr/bin/env python3

import sys
import subprocess

given_exit_status = int(sys.argv[1])
actual_exit_status = subprocess.call(sys.argv[2:])

if actual_exit_status != given_exit_status:
    print(f"FAIL: expected exit status: {hex(given_exit_status)}, actual exit status: {hex(actual_exit_status)}",
          file=sys.stderr)
    sys.exit(1)
